git:
  depth: 1
  submodules: false

matrix:
  include:
      - env: DOCKERFILE="Dockerfile" TARGET_IMAGE="feelpp/quickstart:latest"
        sudo: required
        services:
            - docker
            
before_install:
  - echo $TRAVIS_OS_NAME
  - echo $HOME
  - docker --version
  - sudo apt-get update
  - sudo apt-get install -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
  - git clone --depth=1 https://github.com/feelpp/docker
  - cd docker/dockerfiles/project && docker build -f ${DOCKERFILE} -t ${TARGET_IMAGE} --build-arg=PROJECT_NAME=quickstart --build-arg=GIT_URL=https://github.com/feelpp/quickstart --build-arg=BUILD_JOBS=1 .
  
install:
- docker run feelpp/develop:latest true

script:
- true

